# Why do I get "Notebook Threw Exception", and with the same notebook, sometimes, I get a successful submission?

**Kilaru Vasudeva** *Sat Jun 15 2024 21:32:39 GMT+0900 (日本標準時)* (1 votes)

I find it wierd. Is it any wrong code specification on myside or it is something on the kaggle backend?



---

 # Comments from other users

> ## OminousDude
> 
> Can I get some more info about this problem? It could be if you don't set a random seed something like a division by zero could occur.
> 
> 
> 


---

