# 提出時のエラー

**Nguyễn Anh Tú** *2024年7月15日 月曜日 16:23:48 日本標準時* (0票)
ノートブックを提出した際に「Submission Scoring Error」というエラーが発生しました。提出ファイルのフォーマットが間違っているのではないかと考え、`submission.csv` のフォーマットを確認し、`['winner_model_a', 'winner_model_b', 'winner_tie']` 列の値を自分の `y_predict` で置き換えました。最悪なことに、ノートブックは正常に実行されたのですが、再度提出したところ「Notebook Threw Exception」というエラーが発生しました。助けてください！
---
# 他のユーザーからのコメント
> ## Valentin Werner
> 
> ### 提出スコアエラー -> `id` を含めることを確認してください
> 
> 動作する提出ファイルの例：
> 
> ```
> # 提出
> sub = pd.DataFrame(sm, index = test.id, columns = ["winner_model_a","winner_model_b","winner_tie"]).reset_index()
> sub.to_csv('submission.csv', index=False)
> sub.head()
> 
> ```
> 
> ここで、`sm` は `np.array([0.123,0.567,0.234],…,[0.999,0.000,0.001])` のような配列です。
> 
> ### ノートブックが例外をスローしました
> 
> 動作していたノートブックが動かなくなったんですね 😀 これにはいくつかの理由が考えられます。GPU が OOM になった（これは OOM エラーをトリガーしません）。応答に「null」が含まれていて、処理する必要がある（例えば、文字列表現のリストを実際のリストとして読み込む前に、null を 'null' に置き換える）。実行時に実際にエラーが発生している。
> 
> エラーを評価するためにできることは、推論コードをトレーニングセットの半分（テストのサイズと同じ）で実行してみて、何が起こるかを確認することです。
> 
> 
> 
> > ## Nguyễn Anh Túトピック作成者
> > 
> > とても役に立ちました。ありがとうございます。
> > 
> > 
> > 
---

